CONFIG_ZMK_USB=y
CONFIG_ZMK_SPLIT_BLE=y

CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_OBSERVER=y

CONFIG_ZMK_BLE=y

CONFIG_SETTINGS=y

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y

CONFIG_BT_SETTINGS=y
CONFIG_SETTINGS_NONE=n

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_HID_REPORT_TYPE_HKRO=y
CONFIG_ZMK_HID_CONSUMER_REPORT_SIZE=12
CONFIG_ZMK_HID_KEYBOARD_REPORT_SIZE=12
CONFIG_ZMK_POINTING=y
